env: dev

paths:
  employees: \dataset\employee_records.csv
  sales: \dataset\new_sales.csv
  cities: \dataset\cities.csv
  water_mark: \logs\watermark\watermark.json

output:
  curated: \output\curated
  gold: \output\gold

spark:
  shuffle_partitions: 200