env: prod

paths:
  employees: s3://employee-records-1001/Bronze_Layer/employee_records.csv
  sales: s3://employee-records-1001/Bronze_Layer/new_sales.csv
  cities: s3://employee-records-1001/Bronze_Layer/cities.csv
  water_mark: s3://employee-records-1001/Git-Code/logs/watermark/watermark.json

output:
  curated: s3://employee-records-1001/Curated_Layer/
  gold: s3://employee-records-1001/Gold_Layer/
  employee_dim: s3://employee-records-1001/Gold_layer/employee_dim/
  city_dim: s3://employee-records-1001/Gold_layer/city_dim/
  sales_fact: s3://employee-records-1001/Gold_layer/sales_fact/
  date_dim: s3://employee-records-1001/Gold_layer/date_dim/

spark:
  shuffle_partitions: 50