env: prod

paths:
  employees: s3://employee-records-1001/Bronze_Layer/employee_records.csv
  transactions: s3://employee-records-1001/Bronze_Layer/sales.csv
  cities: s3://employee-records-1001/Bronze_Layer/cities.csv

output:
  curated: s3://employee-records-1001/Curated_Layer/
  gold: s3://employee-records-1001/Gold_Layer/
  

spark:
  shuffle_partitions: 50