name: Integrate ETL to AWS S3 change

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      
    - name: Upload code to S3
      run: |
        aws s3 sync . s3://employee-records-1001/Git-Code/ \
          --exclude ".git/*" \
          --exclude ".github/*"

    # 3️⃣ Package Glue libraries (FROM src/)
    - name: Package Glue libraries
      run: |
        echo "Zipping Glue libraries from src/"
        cd src
        zip -r ../glue_libs.zip utils validations transformations configs ingestion

    - name: Upload Glue main script
      run: |
        aws s3 cp src/main.py \
          s3://employee-records-1001/Git-Code/main.py

    - name: Upload Glue libraries zip
      run: |
        aws s3 cp glue_libs.zip \
          s3://employee-records-1001/Git-Code/libs/glue_libs.zip

    - name: Trigger AWS Glue Job
      run: |
        aws glue start-job-run \
          --job-name SparkJob \
          --arguments '{"--env":"prod"}'